version: "3.8"

services:
  kittinut_project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - trainee-network

networks:
  trainee-network:
    driver: bridge
